server:
  port: 8080

spring:
  application:
    name: ecommerce-service
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    producer:
      properties:
        spring.json.trusted.packages: "*"
      admin:
        properties:
          bootstrap-servers: ${BOOTSTRAP_SERVERS}
        auto-create: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  level:
    com.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
