server:
  port: 8080

spring:
  application:
    name: ecommerce-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: order.created:com.ecommerce.event.OrderCreatedEvent
        retries: 3
        acks: all
        compression-type: snappy
        linger.ms: 5
        batch.size: 16384
        enable.idempotence: true
  security:
    jwt:
      secret: ${JWT_SECRET}


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  level:
    com.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
